Swap out trap and set -e for die()
This avoids dying after any failing shell function call, which is needed
in order to actually log what we want to log for unsupported shells
rather than just dying outright.

There are probably more places where we should `die` eagerly vs continuing
to execute. It's difficult to retrofit sane termination onto something that
eagerly suicided without consideration for why.

Alternatively, we could chain more of our commands together
with `&&`, so that any failure will stop continuing through the
execution chain.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -61,13 +61,19 @@ append_to_shellrc() {
   fi
 }
 
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
 
-set -e
+# die MESSAGE: logs MESSAGE and then exits non-zero
+#
+# Example:
+#
+#     writable "$directory" || die "not writable: $directory"
+die() {
+    local message
 
-
-set -e
+    message="$1"
+    echo "$1" 1>&2
+    exit 1
+}
 
 
 announce_editing_shell_runconfig() {
@@ -90,12 +96,16 @@ ensure_homebrew_prefix_usable() {
   current_group_name="$(id -ng)"
   if [[ -d "$HOMEBREW_PREFIX" ]]; then
     if [[ ! -r "$HOMEBREW_PREFIX" ]]; then
-      sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX"
+      sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
+          || die "failed to change ownership of $HOMEBREW_PREFIX"
     fi
   else
-    sudo mkdir "$HOMEBREW_PREFIX"
-    sudo chflags norestricted "$HOMEBREW_PREFIX"
-    sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX"
+    sudo mkdir "$HOMEBREW_PREFIX" \
+      || die "failed to mkdir $HOMEBREW_PREFIX"
+    sudo chflags norestricted "$HOMEBREW_PREFIX" \
+      || die "failed to chflags norestricted $HOMEBREW_PREFIX"
+    sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
+      || die "failed to change ownership of $HOMEBREW_PREFIX"
   fi
 }
 
@@ -115,7 +125,8 @@ update_homebrew() {
 
   if brew list | grep -Fq brew-cask; then
     fancy_echo "Uninstalling old Homebrew-Cask ..."
-    brew uninstall --force brew-cask
+    brew uninstall --force brew-cask \
+      || die "failed to uninstall brew-cask"
   fi
 
   fancy_echo "Updating Homebrew formulae ..."
@@ -191,7 +202,6 @@ run_bootstrap_local() {
 }
 
 
-set -x
 main() {
   announce_editing_shell_runconfig
   ensure_homebrew_prefix_usable
