ensure_homebrew_prefix_usable: Provide context for password prompt
If we're going to prompt for a password, we ought to tell people
what we plan to do. If they trust us, they can enter their password,
otherwise, they can bail and then do it themselves.

Also provide some "here's what we're doing, here's what we did"
signposting. It's not THE UNIX(TM) WAY, but some of these functions are
REALLY slow to execute. (Switching to a Makefile, which autologs the
commands that it's going to run unless suppressed with `@`,
might be more NIXy.)

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -86,6 +86,7 @@ announce_editing_shell_runconfig() {
 
 
 ensure_homebrew_prefix_usable() {
+  echo "$FUNCNAME: Your Homebrew prefix is ${HOMEBREW_PREFIX:-/usr/local}. Let's ensure it's usable by Homebrew (it exists as a directory, and you can write to it)."
   HOMEBREW_PREFIX="$(brew --prefix)"
   if [[ ! -e "$HOMEBREW_PREFIX" ]]; then
     HOMEBREW_PREFIX="/usr/local"
@@ -93,18 +94,35 @@ ensure_homebrew_prefix_usable() {
 
   current_group_name="$(id -ng)"
   if [[ -d "$HOMEBREW_PREFIX" ]]; then
-    if [[ ! -r "$HOMEBREW_PREFIX" ]]; then
-      sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
+    # brew update requires that HOMEBREW_PREFIX be writeable.
+    if [[ ! -w "$HOMEBREW_PREFIX" ]]; then
+      # chown -R was taking a glacial age to run,
+      # especially when the actual problem was the Google App Engine installer
+      # had decided that /usr/local itself should be owned by root:wheel.
+      # Thanks, Google!
+      #
+      # The -R looks like it works bottom-up, since it hadn't affected the
+      # actual target directory when I bailed, so let's hit that first
+      # in case the user decides to bail out during.
+      fancy_echo "Your password is required to run:
+    chown $LOGNAME:$current_group_name $HOMEBREW_PREFIX
+    && chown -R $LOGNAME:$current_group_name $HOMEBREW_PREFIX/*"
+      sudo chown "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
+          && sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
           || die "failed to change ownership of $HOMEBREW_PREFIX"
     fi
   else
+    fancy_echo "Your password is required to run:
+    mkdir $HOMEBREW_PREFIX
+    && chflags norestricted $HOMEBREW_PREFIX
+    && chown -R $LOGNAME:$current_group_name $HOMEBREW_PREFIX"
     sudo mkdir "$HOMEBREW_PREFIX" \
-      || die "failed to mkdir $HOMEBREW_PREFIX"
-    sudo chflags norestricted "$HOMEBREW_PREFIX" \
-      || die "failed to chflags norestricted $HOMEBREW_PREFIX"
-    sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
-      || die "failed to change ownership of $HOMEBREW_PREFIX"
+      && sudo chflags norestricted "$HOMEBREW_PREFIX" \
+      && sudo chown -R "$LOGNAME:$current_group_name" "$HOMEBREW_PREFIX" \
+      || die "failed to make $HOMEBREW_PREFIX usable"
   fi
+
+  echo "$FUNCNAME: $HOMEBREW_PREFIX should be usable by homebrew now."
 }
 
 update_homebrew() {
